"""HTML element factory constants.

Each ``NAME`` below is a callable that builds the corresponding HTML element.
"""

from functools import partial

from webcompy.elements.generators import break_line, create_element, text

TEXT = text
BR = lambda: break_line()
"""HTML ``<br>`` element factory."""
ADDRESS = partial(create_element, "address")
"""HTML ``<address>`` element factory."""
ARTICLE = partial(create_element, "article")
"""HTML ``<article>`` element factory."""
ASIDE = partial(create_element, "aside")
"""HTML ``<aside>`` element factory."""
FOOTER = partial(create_element, "footer")
"""HTML ``<footer>`` element factory."""
HEADER = partial(create_element, "header")
"""HTML ``<header>`` element factory."""
H1 = partial(create_element, "h1")
"""HTML ``<h1>`` element factory."""
H2 = partial(create_element, "h2")
"""HTML ``<h2>`` element factory."""
H3 = partial(create_element, "h3")
"""HTML ``<h3>`` element factory."""
H4 = partial(create_element, "h4")
"""HTML ``<h4>`` element factory."""
H5 = partial(create_element, "h5")
"""HTML ``<h5>`` element factory."""
H6 = partial(create_element, "h6")
"""HTML ``<h6>`` element factory."""
MAIN = partial(create_element, "main")
"""HTML ``<main>`` element factory."""
NAV = partial(create_element, "nav")
"""HTML ``<nav>`` element factory."""
SECTION = partial(create_element, "section")
"""HTML ``<section>`` element factory."""
BLOCKQUOTE = partial(create_element, "blockquote")
"""HTML ``<blockquote>`` element factory."""
DD = partial(create_element, "dd")
"""HTML ``<dd>`` element factory."""
DIV = partial(create_element, "div")
"""HTML ``<div>`` element factory."""
DL = partial(create_element, "dl")
"""HTML ``<dl>`` element factory."""
DT = partial(create_element, "dt")
"""HTML ``<dt>`` element factory."""
FIGCAPTION = partial(create_element, "figcaption")
"""HTML ``<figcaption>`` element factory."""
FIGURE = partial(create_element, "figure")
"""HTML ``<figure>`` element factory."""
HR = partial(create_element, "hr")
"""HTML ``<hr>`` element factory."""
LI = partial(create_element, "li")
"""HTML ``<li>`` element factory."""
MENU = partial(create_element, "menu")
"""HTML ``<menu>`` element factory."""
OL = partial(create_element, "ol")
"""HTML ``<ol>`` element factory."""
P = partial(create_element, "p")
"""HTML ``<p>`` element factory."""
PRE = partial(create_element, "pre")
"""HTML ``<pre>`` element factory."""
UL = partial(create_element, "ul")
"""HTML ``<ul>`` element factory."""
A = partial(create_element, "a")
"""HTML ``<a>`` element factory."""
ABBR = partial(create_element, "abbr")
"""HTML ``<abbr>`` element factory."""
B = partial(create_element, "b")
"""HTML ``<b>`` element factory."""
BDI = partial(create_element, "bdi")
"""HTML ``<bdi>`` element factory."""
BDO = partial(create_element, "bdo")
"""HTML ``<bdo>`` element factory."""
CITE = partial(create_element, "cite")
"""HTML ``<cite>`` element factory."""
CODE = partial(create_element, "code")
"""HTML ``<code>`` element factory."""
DATA = partial(create_element, "data")
"""HTML ``<data>`` element factory."""
DFN = partial(create_element, "dfn")
"""HTML ``<dfn>`` element factory."""
EM = partial(create_element, "em")
"""HTML ``<em>`` element factory."""
I = partial(create_element, "i")  # noqa: E741
"""HTML ``<i>`` element factory."""
KBD = partial(create_element, "kbd")
"""HTML ``<kbd>`` element factory."""
MARK = partial(create_element, "mark")
"""HTML ``<mark>`` element factory."""
Q = partial(create_element, "q")
"""HTML ``<q>`` element factory."""
RP = partial(create_element, "rp")
"""HTML ``<rp>`` element factory."""
RT = partial(create_element, "rt")
"""HTML ``<rt>`` element factory."""
RUBY = partial(create_element, "ruby")
"""HTML ``<ruby>`` element factory."""
S = partial(create_element, "s")
"""HTML ``<s>`` element factory."""
SAMP = partial(create_element, "samp")
"""HTML ``<samp>`` element factory."""
SMALL = partial(create_element, "small")
"""HTML ``<small>`` element factory."""
SPAN = partial(create_element, "span")
"""HTML ``<span>`` element factory."""
STRONG = partial(create_element, "strong")
"""HTML ``<strong>`` element factory."""
SUB = partial(create_element, "sub")
"""HTML ``<sub>`` element factory."""
SUP = partial(create_element, "sup")
"""HTML ``<sup>`` element factory."""
TIME = partial(create_element, "time")
"""HTML ``<time>`` element factory."""
U = partial(create_element, "u")
"""HTML ``<u>`` element factory."""
VAR = partial(create_element, "var")
"""HTML ``<var>`` element factory."""
WBR = partial(create_element, "wbr")
"""HTML ``<wbr>`` element factory."""
AREA = partial(create_element, "area")
"""HTML ``<area>`` element factory."""
AUDIO = partial(create_element, "audio")
"""HTML ``<audio>`` element factory."""
IMG = partial(create_element, "img")
"""HTML ``<img>`` element factory."""
MAP = partial(create_element, "map")
"""HTML ``<map>`` element factory."""
TRACK = partial(create_element, "track")
"""HTML ``<track>`` element factory."""
VIDEO = partial(create_element, "video")
"""HTML ``<video>`` element factory."""
EMBED = partial(create_element, "embed")
"""HTML ``<embed>`` element factory."""
IFRAME = partial(create_element, "iframe")
"""HTML ``<iframe>`` element factory."""
OBJECT = partial(create_element, "object")
"""HTML ``<object>`` element factory."""
PARAM = partial(create_element, "param")
"""HTML ``<param>`` element factory."""
PICTURE = partial(create_element, "picture")
"""HTML ``<picture>`` element factory."""
PORTAL = partial(create_element, "portal")
"""HTML ``<portal>`` element factory."""
SOURCE = partial(create_element, "source")
"""HTML ``<source>`` element factory."""
SVG = partial(create_element, "svg")
"""HTML ``<svg>`` element factory."""
MATH = partial(create_element, "math")
"""HTML ``<math>`` element factory."""
CANVAS = partial(create_element, "canvas")
"""HTML ``<canvas>`` element factory."""
DEL = partial(create_element, "del")
"""HTML ``<del>`` element factory."""
INS = partial(create_element, "ins")
"""HTML ``<ins>`` element factory."""
CAPTION = partial(create_element, "caption")
"""HTML ``<caption>`` element factory."""
COL = partial(create_element, "col")
"""HTML ``<col>`` element factory."""
COLGROUP = partial(create_element, "colgroup")
"""HTML ``<colgroup>`` element factory."""
TABLE = partial(create_element, "table")
"""HTML ``<table>`` element factory."""
TBODY = partial(create_element, "tbody")
"""HTML ``<tbody>`` element factory."""
TD = partial(create_element, "td")
"""HTML ``<td>`` element factory."""
TFOOT = partial(create_element, "tfoot")
"""HTML ``<tfoot>`` element factory."""
TH = partial(create_element, "th")
"""HTML ``<th>`` element factory."""
THEAD = partial(create_element, "thead")
"""HTML ``<thead>`` element factory."""
TR = partial(create_element, "tr")
"""HTML ``<tr>`` element factory."""
BUTTON = partial(create_element, "button")
"""HTML ``<button>`` element factory."""
DATALIST = partial(create_element, "datalist")
"""HTML ``<datalist>`` element factory."""
FIELDSET = partial(create_element, "fieldset")
"""HTML ``<fieldset>`` element factory."""
FORM = partial(create_element, "form")
"""HTML ``<form>`` element factory."""
INPUT = partial(create_element, "input")
"""HTML ``<input>`` element factory."""
LABEL = partial(create_element, "label")
"""HTML ``<label>`` element factory."""
LEGEND = partial(create_element, "legend")
"""HTML ``<legend>`` element factory."""
METER = partial(create_element, "meter")
"""HTML ``<meter>`` element factory."""
OPTGROUP = partial(create_element, "optgroup")
"""HTML ``<optgroup>`` element factory."""
OPTION = partial(create_element, "option")
"""HTML ``<option>`` element factory."""
OUTPUT = partial(create_element, "output")
"""HTML ``<output>`` element factory."""
PROGRESS = partial(create_element, "progress")
"""HTML ``<progress>`` element factory."""
SELECT = partial(create_element, "select")
"""HTML ``<select>`` element factory."""
TEXTAREA = partial(create_element, "textarea")
"""HTML ``<textarea>`` element factory."""
DETAILS = partial(create_element, "details")
"""HTML ``<details>`` element factory."""
DIALOG = partial(create_element, "dialog")
"""HTML ``<dialog>`` element factory."""
SUMMARY = partial(create_element, "summary")
"""HTML ``<summary>`` element factory."""
