blank_issues_enabled: false
contact_links:
  - name: Discussion / Question
    url: https://github.com/kniwase/WebComPy/discussions
    about: Please use Discussions for questions and general discussion
