from typing import Any, ClassVar

from webcompy.app._app import WebComPyApp
from webcompy.app._config import PluginScript

class WebComPyPluginException(Exception): ...

class WebComPyPlugin:
    name: ClassVar[str] = ""
    version: ClassVar[str] = "0.1.0"

    @staticmethod
    def get_providers() -> dict[object, Any]: ...
    @staticmethod
    def get_scripts() -> list[PluginScript]: ...
    def on_app_init(self, app: WebComPyApp) -> None: ...
    def on_app_ready(self, app: WebComPyApp) -> None: ...

class PluginManager:
    def __init__(self, app: WebComPyApp) -> None: ...
    def discover(self, plugin_paths: list[str]) -> None: ...
    def init_all(self) -> None: ...
    def call_on_app_ready(self, app: WebComPyApp) -> None: ...
    @property
    def scripts(self) -> list[PluginScript]: ...
