from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, Protocol


class DOMNode(Protocol):
    @property
    def __webcompy_node__(self) -> bool: ...
    @__webcompy_node__.setter
    def __webcompy_node__(self, value: bool) -> None: ...

    @property
    def __webcompy_prerendered_node__(self) -> bool: ...
    @__webcompy_prerendered_node__.setter
    def __webcompy_prerendered_node__(self, value: bool) -> None: ...

    def appendChild(self, child: DOMNode) -> None: ...
    def removeChild(self, child: DOMNode) -> None: ...
    def insertBefore(self, new_node: DOMNode, ref_node: DOMNode) -> None: ...
    def replaceChild(self, new_node: DOMNode, old_node: DOMNode) -> None: ...
    def remove(self) -> None: ...

    def setAttribute(self, name: str, value: str) -> None: ...
    def getAttribute(self, name: str) -> str | None: ...
    def removeAttribute(self, name: str) -> None: ...
    def hasAttribute(self, name: str) -> bool: ...
    def getAttributeNames(self) -> list[str]: ...

    def addEventListener(
        self,
        event_type: str,
        handler: Any,
        options_or_capture: Any = False,
    ) -> None: ...
    def removeEventListener(
        self,
        event_type: str,
        handler: Any,
        options_or_capture: Any = False,
    ) -> None: ...

    @property
    def textContent(self) -> str | None: ...

    @textContent.setter
    def textContent(self, value: str | None) -> None: ...

    @property
    def childNodes(self) -> DOMNodeList: ...

    @property
    def parentNode(self) -> DOMNode | None: ...

    @property
    def nodeName(self) -> str: ...

    @property
    def nodeType(self) -> int: ...


class DOMNodeList:
    def __init__(self, nodes: list[DOMNode]) -> None:
        self._nodes = nodes

    @property
    def length(self) -> int:
        return len(self._nodes)

    def __getitem__(self, index: int) -> DOMNode:
        return self._nodes[index]


class DOMPort(ABC):
    @abstractmethod
    def create_element(self, tag: str) -> DOMNode: ...
    @abstractmethod
    def create_text_node(self, text: str) -> DOMNode: ...
    @abstractmethod
    def query_selector(self, selector: str) -> DOMNode | None: ...
    @abstractmethod
    def get_element_by_id(self, element_id: str) -> DOMNode | None: ...
    @abstractmethod
    def set_title(self, title: str) -> None: ...
    @abstractmethod
    def schedule_macro_task(self, callback: Any) -> None: ...
