# ruff: noqa: RUF001
from __future__ import annotations

import os
import pathlib
import re
import shutil
import subprocess
import sys
import tomllib

from webcompy.app._config import LockfileSyncConfig
from webcompy.cli._exception import WebComPyCliException
from webcompy.cli._lockfile import Lockfile


def discover_project_root(app_package_path: pathlib.Path) -> pathlib.Path:
    for dir_path in [app_package_path, *app_package_path.parents]:
        if (dir_path / "pyproject.toml").exists():
            return dir_path
    raise WebComPyCliException(
        f"Could not find pyproject.toml above {app_package_path}. "
        "Set LockfileSyncConfig.requirements_path in webcompy_server_config.py."
    )


def discover_requirements_path(
    app_package_path: pathlib.Path,
    lockfile_sync_config: LockfileSyncConfig | None = None,
) -> pathlib.Path:
    if lockfile_sync_config is not None and lockfile_sync_config.requirements_path is not None:
        path = pathlib.Path(lockfile_sync_config.requirements_path)
        if path.is_absolute():
            return path
        return (app_package_path / path).resolve()
    project_root = discover_project_root(app_package_path)
    return project_root / "requirements.txt"


def export_requirements(
    lockfile: Lockfile,
    path: pathlib.Path,
) -> None:
    entries: list[tuple[str, str]] = []
    for name, entry in lockfile.bundled_packages.items():
        entries.append((name, entry.version))
    for name, entry in lockfile.pyodide_packages.items():
        if not entry.is_wasm:
            entries.append((name, entry.version))
    entries.sort(key=lambda x: x[0].lower())
    lines = ["# Generated by webcompy lock --export", ""]
    for name, version in entries:
        lines.append(f"{name}=={version}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def record_requirements_path(
    app_package_path: pathlib.Path,
    requirements_path: pathlib.Path,
    config_module_path: pathlib.Path | None = None,
) -> None:
    try:
        rel_path = os.path.relpath(str(requirements_path), str(app_package_path))
    except ValueError:
        return

    def _find_config_module() -> pathlib.Path | None:
        if config_module_path is not None:
            return config_module_path
        for candidate in [
            app_package_path / "webcompy_server_config.py",
        ]:
            if candidate.exists():
                return candidate
        for dir_path in app_package_path.parents:
            candidate = dir_path / "webcompy_server_config.py"
            if candidate.exists():
                return candidate
        return None

    config_path = _find_config_module()
    if config_path is None or not config_path.exists():
        print(
            f"Warning: Could not find webcompy_server_config.py to record requirements_path. "
            f"Please add: lockfile_sync_config = LockfileSyncConfig(requirements_path='{rel_path}')",
            file=sys.stderr,
        )
        return
    source = config_path.read_text(encoding="utf-8")
    has_lockfile_sync_import = "LockfileSyncConfig" in source
    has_lockfile_sync_config = "lockfile_sync_config" in source
    if has_lockfile_sync_config:
        print(
            f"Note: lockfile_sync_config already exists in {config_path}. "
            f"If requirements_path is not set, consider updating it to: "
            f"LockfileSyncConfig(requirements_path='{rel_path}')",
            file=sys.stderr,
        )
        return
    new_lines = []
    if not has_lockfile_sync_import:
        new_lines.append("from webcompy.app._config import LockfileSyncConfig")
    new_lines.append(f"lockfile_sync_config = LockfileSyncConfig(requirements_path='{rel_path}')")
    with open(config_path, "a", encoding="utf-8") as f:
        f.write("\n" + "\n".join(new_lines) + "\n")
    print(f"Recorded requirements_path='{rel_path}' in {config_path}")


def sync_from_requirements_txt(
    lockfile: Lockfile,
    path: pathlib.Path,
) -> list[str]:
    if not path.exists():
        return [f"ℹ No requirements.txt found at {path}"]
    text = path.read_text(encoding="utf-8")
    entries: dict[str, str] = {}
    unpinned: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        match = re.match(r"^([a-zA-Z0-9_.-]+)==([a-zA-Z0-9_.+!-]+)$", stripped)
        if match:
            name, version = match.group(1), match.group(2)
            normalized = name.lower().replace("-", "_")
            entries[normalized] = version
        elif re.match(r"^([a-zA-Z0-9_.-]+)", stripped):
            name_match = re.match(r"^([a-zA-Z0-9_.-]+)", stripped)
            if name_match:
                unpinned.append(name_match.group(1))
    lockfile_pkgs: dict[str, tuple[str, str]] = {}
    for name, entry in lockfile.bundled_packages.items():
        lockfile_pkgs[name.lower().replace("-", "_")] = (name, entry.version)
    for name, entry in lockfile.pyodide_packages.items():
        if not entry.is_wasm:
            lockfile_pkgs[name.lower().replace("-", "_")] = (name, entry.version)
    wasm_pkgs: set[str] = set()
    for name, entry in lockfile.pyodide_packages.items():
        if entry.is_wasm:
            wasm_pkgs.add(name.lower().replace("-", "_"))
    lines: list[str] = []
    seen: set[str] = set()
    for normalized, version in sorted(entries.items()):
        seen.add(normalized)
        if normalized in lockfile_pkgs:
            lock_name, lock_version = lockfile_pkgs[normalized]
            if version == lock_version:
                lines.append(f"✓ {lock_name}: {version} (matches)")
            else:
                lines.append(
                    f"⚠ {lock_name}: lock={lock_version}, requirements.txt={version} (mismatch) "
                    f"Suggest: pip install {lock_name}=={lock_version}"
                )
        elif normalized in wasm_pkgs:
            lines.append(f"ℹ {normalized}: WASM package, not applicable for local install")
        else:
            lines.append(f"ℹ {normalized}: not in lock file (non-browser dependency?)")
    for name in sorted(unpinned):
        normalized = name.lower().replace("-", "_")
        if normalized in seen:
            continue
        if normalized in lockfile_pkgs:
            lock_name, lock_version = lockfile_pkgs[normalized]
            lines.append(f"ℹ {lock_name}: not pinned in requirements.txt, lock file has {lock_version}")
    return lines


def sync_from_pyproject_toml(
    lockfile: Lockfile,
    path: pathlib.Path,
    sync_group: str | None = None,
) -> list[str]:
    if not path.exists():
        return [f"⚠ No pyproject.toml found at {path}"]
    try:
        with open(path, "rb") as f:
            data = tomllib.load(f)
    except Exception as e:
        return [f"⚠ Error parsing pyproject.toml: {e}"]
    if sync_group is None:
        deps = data.get("project", {}).get("dependencies", [])
        if not deps:
            return ["ℹ No [project.dependencies] found in pyproject.toml"]
    else:
        opt_deps = data.get("project", {}).get("optional-dependencies", None)
        if opt_deps is None:
            return ["⚠ No [project.optional-dependencies] found in pyproject.toml"]
        deps = opt_deps.get(sync_group, None)
        if deps is None:
            return [f"⚠ No [project.optional-dependencies.{sync_group}] found in pyproject.toml"]
    lockfile_pkgs: dict[str, tuple[str, str]] = {}
    for name, entry in lockfile.bundled_packages.items():
        lockfile_pkgs[name.lower().replace("-", "_")] = (name, entry.version)
    for name, entry in lockfile.pyodide_packages.items():
        if not entry.is_wasm:
            lockfile_pkgs[name.lower().replace("-", "_")] = (name, entry.version)
    wasm_pkgs: set[str] = set()
    for name, entry in lockfile.pyodide_packages.items():
        if entry.is_wasm:
            wasm_pkgs.add(name.lower().replace("-", "_"))
    lines: list[str] = []
    pinned_re = re.compile(r"^([a-zA-Z0-9_.-]+)==([a-zA-Z0-9_.+!-]+)$")
    range_re = re.compile(r"^([a-zA-Z0-9_.-]+)([><=!~].+)$")
    bare_re = re.compile(r"^([a-zA-Z0-9_.-]+)$")
    for dep in deps:
        pin_match = pinned_re.match(dep)
        range_match = range_re.match(dep)
        bare_match = bare_re.match(dep)
        if pin_match:
            name, version = pin_match.group(1), pin_match.group(2)
            normalized = name.lower().replace("-", "_")
            if normalized in lockfile_pkgs:
                lock_name, lock_version = lockfile_pkgs[normalized]
                if version == lock_version:
                    lines.append(f"✓ {lock_name}: {version} (matches)")
                else:
                    lines.append(
                        f"⚠ {lock_name}: lock={lock_version}, pyproject.toml={version} (mismatch) "
                        f"Suggest: pip install {lock_name}=={lock_version}"
                    )
            elif normalized in wasm_pkgs:
                lines.append(f"ℹ {name}: WASM package, not applicable for local install")
            else:
                lines.append(f"ℹ {name}: not in lock file (non-browser dependency?)")
        elif range_match:
            name, specifier = range_match.group(1), range_match.group(2)
            normalized = name.lower().replace("-", "_")
            if normalized in lockfile_pkgs:
                lock_name, lock_version = lockfile_pkgs[normalized]
                lines.append(
                    f'ℹ {lock_name}: not pinned ("{specifier}"), lock file has {lock_version} Suggest: pin to {lock_name}=={lock_version}'
                )
            elif normalized in wasm_pkgs:
                lines.append(f"ℹ {name}: WASM package, not applicable for local install")
            else:
                lines.append(f'ℹ {name}: not pinned ("{specifier}"), not in lock file')
        elif bare_match:
            name = bare_match.group(1)
            normalized = name.lower().replace("-", "_")
            if normalized in lockfile_pkgs:
                lock_name, lock_version = lockfile_pkgs[normalized]
                lines.append(f"ℹ {lock_name}: no version specifier, lock file has {lock_version}")
            elif normalized in wasm_pkgs:
                lines.append(f"ℹ {name}: WASM package, not applicable for local install")
            else:
                lines.append(f"ℹ {name}: no version specifier, not in lock file")
        else:
            lines.append(f"ℹ Could not parse dependency: {dep}")
    return lines


def sync(
    lockfile: Lockfile,
    project_root: pathlib.Path,
    sync_group: str | None = None,
) -> list[str]:
    lines: list[str] = []
    req_path = project_root / "requirements.txt"
    pyproject_path = project_root / "pyproject.toml"
    if req_path.exists():
        lines.append("--- requirements.txt ---")
        lines.extend(sync_from_requirements_txt(lockfile, req_path))
    if pyproject_path.exists():
        if sync_group is None:
            lines.append("--- pyproject.toml [project.dependencies] ---")
        else:
            lines.append(f"--- pyproject.toml [project.optional-dependencies.{sync_group}] ---")
        lines.extend(sync_from_pyproject_toml(lockfile, pyproject_path, sync_group))
    if not req_path.exists() and not pyproject_path.exists():
        lines.append(f"⚠ No requirements.txt or pyproject.toml found at {project_root}")
    return lines


def install_requirements(
    lockfile: Lockfile,
    requirements_path: pathlib.Path,
) -> None:
    export_requirements(lockfile, requirements_path)
    if shutil.which("uv"):
        result = subprocess.run(
            ["uv", "pip", "install", "-r", str(requirements_path)],
        )
    else:
        result = subprocess.run(
            [sys.executable, "-m", "pip", "install", "-r", str(requirements_path)],
        )
    if result.returncode != 0:
        sys.exit(result.returncode)


def _parse_dependency_name(dep: str) -> str:
    match = re.match(r"^([a-zA-Z0-9_.-]+)", dep)
    if match:
        return match.group(1)
    return dep


def resolve_dependencies(app, lockfile_sync_config: LockfileSyncConfig | None = None) -> None:
    if app.config.dependencies is not None:
        return
    project_root = discover_project_root(app.config.app_package_path)
    pyproject_path = project_root / "pyproject.toml"
    try:
        with open(pyproject_path, "rb") as f:
            data = tomllib.load(f)
    except Exception as e:
        raise WebComPyCliException(f"Error reading pyproject.toml: {e}") from e
    if app.config.dependencies_from is None:
        deps = data.get("project", {}).get("dependencies", None)
        if deps is None:
            raise WebComPyCliException(
                "No [project.dependencies] found in pyproject.toml. "
                "Set AppConfig.dependencies explicitly or add [project.dependencies]."
            )
    else:
        opt_deps = data.get("project", {}).get("optional-dependencies", None)
        if opt_deps is None:
            raise WebComPyCliException(
                f"No [project.optional-dependencies] found in pyproject.toml. "
                f"Set AppConfig.dependencies explicitly or add [project.optional-dependencies.{app.config.dependencies_from}]."
            )
        deps = opt_deps.get(app.config.dependencies_from, None)
        if deps is None:
            raise WebComPyCliException(
                f"No [project.optional-dependencies.{app.config.dependencies_from}] found in pyproject.toml. "
                f"Set AppConfig.dependencies explicitly or add the optional-dependencies group."
            )
    app.config.dependencies = [_parse_dependency_name(dep) for dep in deps]
    if (
        app.config.dependencies_from is not None
        and lockfile_sync_config is not None
        and lockfile_sync_config.sync_group is not None
        and app.config.dependencies_from != lockfile_sync_config.sync_group
    ):
        print(
            f'⚠ AppConfig.dependencies_from="{app.config.dependencies_from}" differs from '
            f'LockfileSyncConfig.sync_group="{lockfile_sync_config.sync_group}". '
            "This may cause inconsistencies between lock file generation and sync comparison.",
            file=sys.stderr,
        )
